# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import userdoc_pb2 as userdoc__pb2
import requests_pb2 as requests__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x1a\ruserdoc.proto\x1a\x0erequests.proto2u\n\x13UserDocumentService\x12/\n\x0fGetUserDocument\x12\r.QueryForUser\x1a\r.UserDocument\x12-\n\x12\x43reateUserDocument\x12\x08.NewUser\x1a\r.UserDocumentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERDOCUMENTSERVICE']._serialized_start=49
  _globals['_USERDOCUMENTSERVICE']._serialized_end=166
# @@protoc_insertion_point(module_scope)
